/* tslint:disable */
/* eslint-disable */
/**
 * LionPay.Wallet | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ApiV1TransactionsGetLimitParameter {
}
export interface ApiV1TransactionsGetOffsetParameter {
}
export interface ChargeRequest {
    'amount': ChargeRequestAmount;
}
export interface ChargeRequestAmount {
}
export interface ErrorResponse {
    'errorCode': string;
    'errorMessage': string;
}
export interface MerchantResponse {
    'merchantId': string;
    'merchantName': string;
    'countryCode': string;
    'merchantCategory': string;
    'merchantStatus': string;
    'createdAt': string;
}
export interface PaymentRequest {
    'merchantId': string;
    'amountCash': ChargeRequestAmount;
    'currency': string;
    'assetType': string;
}
export interface PaymentResponse {
    'txId': string;
    'merchantId': string;
    'amount': ChargeRequestAmount;
    'txStatus': string;
    'createdAt': string;
}
export interface TransactionResponse {
    'txId': string;
    'merchantId': string;
    'amount': ChargeRequestAmount;
    'txType': string;
    'txStatus': string;
    'merchantName': string;
    'createdAt': string;
}
export interface WalletResponse {
    'walletId': string;
    'balance': ChargeRequestAmount;
    'walletType': string;
    'updatedAt': string;
}

/**
 * MerchantApi - axios parameter creator
 */
export const MerchantApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves details of a specific merchant by ID.
         * @summary Get merchant details
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1MerchantsIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiV1MerchantsIdGet', 'id', id)
            const localVarPath = `/api/v1/merchants/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MerchantApi - functional programming interface
 */
export const MerchantApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MerchantApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves details of a specific merchant by ID.
         * @summary Get merchant details
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1MerchantsIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MerchantResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1MerchantsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MerchantApi.apiV1MerchantsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MerchantApi - factory interface
 */
export const MerchantApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MerchantApiFp(configuration)
    return {
        /**
         * Retrieves details of a specific merchant by ID.
         * @summary Get merchant details
         * @param {MerchantApiApiV1MerchantsIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1MerchantsIdGet(requestParameters: MerchantApiApiV1MerchantsIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<MerchantResponse> {
            return localVarFp.apiV1MerchantsIdGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiV1MerchantsIdGet operation in MerchantApi.
 */
export interface MerchantApiApiV1MerchantsIdGetRequest {
    readonly id: string
}

/**
 * MerchantApi - object-oriented interface
 */
export class MerchantApi extends BaseAPI {
    /**
     * Retrieves details of a specific merchant by ID.
     * @summary Get merchant details
     * @param {MerchantApiApiV1MerchantsIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1MerchantsIdGet(requestParameters: MerchantApiApiV1MerchantsIdGetRequest, options?: RawAxiosRequestConfig) {
        return MerchantApiFp(this.configuration).apiV1MerchantsIdGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PaymentApi - axios parameter creator
 */
export const PaymentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Processes a payment transaction for a user.
         * @summary Process a payment
         * @param {PaymentRequest} paymentRequest 
         * @param {string} [xIdempotencyKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PaymentsPost: async (paymentRequest: PaymentRequest, xIdempotencyKey?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paymentRequest' is not null or undefined
            assertParamExists('apiV1PaymentsPost', 'paymentRequest', paymentRequest)
            const localVarPath = `/api/v1/payments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xIdempotencyKey != null) {
                localVarHeaderParameter['X-Idempotency-Key'] = String(xIdempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(paymentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentApi - functional programming interface
 */
export const PaymentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaymentApiAxiosParamCreator(configuration)
    return {
        /**
         * Processes a payment transaction for a user.
         * @summary Process a payment
         * @param {PaymentRequest} paymentRequest 
         * @param {string} [xIdempotencyKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PaymentsPost(paymentRequest: PaymentRequest, xIdempotencyKey?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PaymentsPost(paymentRequest, xIdempotencyKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentApi.apiV1PaymentsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PaymentApi - factory interface
 */
export const PaymentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaymentApiFp(configuration)
    return {
        /**
         * Processes a payment transaction for a user.
         * @summary Process a payment
         * @param {PaymentApiApiV1PaymentsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PaymentsPost(requestParameters: PaymentApiApiV1PaymentsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<PaymentResponse> {
            return localVarFp.apiV1PaymentsPost(requestParameters.paymentRequest, requestParameters.xIdempotencyKey, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiV1PaymentsPost operation in PaymentApi.
 */
export interface PaymentApiApiV1PaymentsPostRequest {
    readonly paymentRequest: PaymentRequest

    readonly xIdempotencyKey?: string
}

/**
 * PaymentApi - object-oriented interface
 */
export class PaymentApi extends BaseAPI {
    /**
     * Processes a payment transaction for a user.
     * @summary Process a payment
     * @param {PaymentApiApiV1PaymentsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1PaymentsPost(requestParameters: PaymentApiApiV1PaymentsPostRequest, options?: RawAxiosRequestConfig) {
        return PaymentApiFp(this.configuration).apiV1PaymentsPost(requestParameters.paymentRequest, requestParameters.xIdempotencyKey, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TransactionApi - axios parameter creator
 */
export const TransactionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves a list of past transactions for the authenticated user.
         * @summary Get transaction history
         * @param {ApiV1TransactionsGetLimitParameter} [limit] 
         * @param {ApiV1TransactionsGetOffsetParameter} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TransactionsGet: async (limit?: ApiV1TransactionsGetLimitParameter, offset?: ApiV1TransactionsGetOffsetParameter, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransactionApi - functional programming interface
 */
export const TransactionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransactionApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves a list of past transactions for the authenticated user.
         * @summary Get transaction history
         * @param {ApiV1TransactionsGetLimitParameter} [limit] 
         * @param {ApiV1TransactionsGetOffsetParameter} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1TransactionsGet(limit?: ApiV1TransactionsGetLimitParameter, offset?: ApiV1TransactionsGetOffsetParameter, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TransactionResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1TransactionsGet(limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionApi.apiV1TransactionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TransactionApi - factory interface
 */
export const TransactionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransactionApiFp(configuration)
    return {
        /**
         * Retrieves a list of past transactions for the authenticated user.
         * @summary Get transaction history
         * @param {TransactionApiApiV1TransactionsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TransactionsGet(requestParameters: TransactionApiApiV1TransactionsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<TransactionResponse>> {
            return localVarFp.apiV1TransactionsGet(requestParameters.limit, requestParameters.offset, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiV1TransactionsGet operation in TransactionApi.
 */
export interface TransactionApiApiV1TransactionsGetRequest {
    readonly limit?: ApiV1TransactionsGetLimitParameter

    readonly offset?: ApiV1TransactionsGetOffsetParameter
}

/**
 * TransactionApi - object-oriented interface
 */
export class TransactionApi extends BaseAPI {
    /**
     * Retrieves a list of past transactions for the authenticated user.
     * @summary Get transaction history
     * @param {TransactionApiApiV1TransactionsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1TransactionsGet(requestParameters: TransactionApiApiV1TransactionsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return TransactionApiFp(this.configuration).apiV1TransactionsGet(requestParameters.limit, requestParameters.offset, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WalletApi - axios parameter creator
 */
export const WalletApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Charges the user\'s wallet with the specified amount.
         * @summary Charge wallet
         * @param {ChargeRequest} chargeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletsChargePost: async (chargeRequest: ChargeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chargeRequest' is not null or undefined
            assertParamExists('apiV1WalletsChargePost', 'chargeRequest', chargeRequest)
            const localVarPath = `/api/v1/wallets/charge`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(chargeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the current user\'s wallet information.
         * @summary Get my wallet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletsMeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/wallets/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WalletApi - functional programming interface
 */
export const WalletApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WalletApiAxiosParamCreator(configuration)
    return {
        /**
         * Charges the user\'s wallet with the specified amount.
         * @summary Charge wallet
         * @param {ChargeRequest} chargeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletsChargePost(chargeRequest: ChargeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WalletResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletsChargePost(chargeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WalletApi.apiV1WalletsChargePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves the current user\'s wallet information.
         * @summary Get my wallet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletsMeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WalletResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletsMeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WalletApi.apiV1WalletsMeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WalletApi - factory interface
 */
export const WalletApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WalletApiFp(configuration)
    return {
        /**
         * Charges the user\'s wallet with the specified amount.
         * @summary Charge wallet
         * @param {WalletApiApiV1WalletsChargePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletsChargePost(requestParameters: WalletApiApiV1WalletsChargePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<WalletResponse> {
            return localVarFp.apiV1WalletsChargePost(requestParameters.chargeRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the current user\'s wallet information.
         * @summary Get my wallet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletsMeGet(options?: RawAxiosRequestConfig): AxiosPromise<WalletResponse> {
            return localVarFp.apiV1WalletsMeGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiV1WalletsChargePost operation in WalletApi.
 */
export interface WalletApiApiV1WalletsChargePostRequest {
    readonly chargeRequest: ChargeRequest
}

/**
 * WalletApi - object-oriented interface
 */
export class WalletApi extends BaseAPI {
    /**
     * Charges the user\'s wallet with the specified amount.
     * @summary Charge wallet
     * @param {WalletApiApiV1WalletsChargePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletsChargePost(requestParameters: WalletApiApiV1WalletsChargePostRequest, options?: RawAxiosRequestConfig) {
        return WalletApiFp(this.configuration).apiV1WalletsChargePost(requestParameters.chargeRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the current user\'s wallet information.
     * @summary Get my wallet
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletsMeGet(options?: RawAxiosRequestConfig) {
        return WalletApiFp(this.configuration).apiV1WalletsMeGet(options).then((request) => request(this.axios, this.basePath));
    }
}



