/* tslint:disable */
/* eslint-disable */
/**
 * LionPay.Wallet | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AdjustBalanceRequest {
    'amount': AdjustBalanceRequestAmount;
    'reason': string;
}
export interface AdjustBalanceRequestAmount {
}
export interface AdminSummaryModel {
    'totalWallets': AdminSummaryModelTotalWallets;
    'totalMerchants': AdminSummaryModelTotalWallets;
    'totalTransactions': AdminSummaryModelTotalWallets;
    'activeCurrencies': ApiV1WalletAdminExchangeRatesHistoryGetLimitParameter;
}
export interface AdminSummaryModelTotalWallets {
}
export interface ApiV1WalletAdminExchangeRatesHistoryGetLimitParameter {
}
export interface ApiV1WalletTransactionsGetLimitParameter {
}
export interface ApiV1WalletTransactionsGetOffsetParameter {
}
export interface ChargeRequest {
    'amount': AdjustBalanceRequestAmount;
}
export interface CreateMerchantRequest {
    'merchantName': string;
    'countryCode': string;
    'merchantCategory': string;
}
export interface CurrencyResponse {
    'currencyCode': string;
    'currencyName': string;
    'symbol': string | null;
    'isActive': boolean;
}
export interface ErrorResponse {
    'errorCode': string;
    'errorMessage': string;
}
export interface ExchangeRateHistoryResponse {
    'id': string;
    'exchangeRateId': string;
    'sourceCurrency': string;
    'targetCurrency': string;
    'oldRate': ExchangeRateHistoryResponseOldRate | null;
    'newRate': AdjustBalanceRequestAmount;
    'changedAt': string;
    'changedBy': string | null;
}
export interface ExchangeRateHistoryResponseOldRate {
}
export interface ExchangeRateResponse {
    'id': string;
    'sourceCurrency': string;
    'targetCurrency': string;
    'rate': AdjustBalanceRequestAmount;
    'rateType': RateType;
    'source': ExchangeRateSource;
    'updatedAt': string;
}



export const ExchangeRateSource = {
    Manual: 'Manual',
    System: 'System',
    Api: 'Api'
} as const;

export type ExchangeRateSource = typeof ExchangeRateSource[keyof typeof ExchangeRateSource];


export interface MerchantModel {
    'merchantId'?: string;
    'merchantName'?: string;
    'countryCode'?: string;
    'merchantCategory'?: string;
    'merchantStatus'?: MerchantStatus;
    'createdAt'?: string;
}


export interface MerchantResponse {
    'merchantId': string;
    'merchantName': string;
    'countryCode': string;
    'merchantCategory': string;
    'merchantStatus': MerchantStatus;
    'createdAt': string;
}



export const MerchantStatus = {
    Inactive: 'Inactive',
    Active: 'Active',
    Suspended: 'Suspended'
} as const;

export type MerchantStatus = typeof MerchantStatus[keyof typeof MerchantStatus];


export interface PaymentRequest {
    'merchantId': string;
    'amountCash': AdjustBalanceRequestAmount;
    'currency': string;
}
export interface PaymentResponse {
    'txId': string;
    'merchantId': string;
    'amount': AdjustBalanceRequestAmount;
    'txStatus': TxStatus;
    'createdAt': string;
}



export const RateType = {
    Close: 'Close',
    Open: 'Open'
} as const;

export type RateType = typeof RateType[keyof typeof RateType];


export interface TransactionResponse {
    'txId': string;
    'merchantId': string;
    'amount': AdjustBalanceRequestAmount;
    'txType': TxType;
    'txStatus': TxStatus;
    'merchantName': string;
    'balanceAfter': AdjustBalanceRequestAmount;
    'currency': string;
    'originalAmount': AdjustBalanceRequestAmount;
    'createdAt': string;
}



export const TxStatus = {
    Success: 'Success',
    Failed: 'Failed'
} as const;

export type TxStatus = typeof TxStatus[keyof typeof TxStatus];



export const TxType = {
    Payment: 'Payment',
    Charge: 'Charge',
    AdminCharge: 'AdminCharge',
    AdminDeduct: 'AdminDeduct'
} as const;

export type TxType = typeof TxType[keyof typeof TxType];


export interface UpdateExchangeRateRequest {
    'sourceCurrency': string;
    'targetCurrency': string;
    'rate': AdjustBalanceRequestAmount;
}
export interface UpdateMerchantRequest {
    'merchantName': string;
    'merchantCategory': string;
    'merchantStatus': MerchantStatus;
}


export interface WalletResponse {
    'walletId': string;
    'balance': AdjustBalanceRequestAmount;
    'walletType': WalletType;
    'updatedAt': string;
}



export const WalletType = {
    Money: 'Money',
    Point: 'Point'
} as const;

export type WalletType = typeof WalletType[keyof typeof WalletType];



/**
 * AdminApi - axios parameter creator
 */
export const AdminApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all currencies (admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminExchangeRatesCurrenciesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/wallet/admin/exchange-rates/currencies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all exchange rates (admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminExchangeRatesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/wallet/admin/exchange-rates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the history of exchange rate changes.
         * @summary Get exchange rate history
         * @param {ApiV1WalletAdminExchangeRatesHistoryGetLimitParameter} limit 
         * @param {string} [sourceCurrency] 
         * @param {string} [targetCurrency] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminExchangeRatesHistoryGet: async (limit: ApiV1WalletAdminExchangeRatesHistoryGetLimitParameter, sourceCurrency?: string, targetCurrency?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'limit' is not null or undefined
            assertParamExists('apiV1WalletAdminExchangeRatesHistoryGet', 'limit', limit)
            const localVarPath = `/api/v1/wallet/admin/exchange-rates/history`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sourceCurrency !== undefined) {
                localVarQueryParameter['sourceCurrency'] = sourceCurrency;
            }

            if (targetCurrency !== undefined) {
                localVarQueryParameter['targetCurrency'] = targetCurrency;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create or update an exchange rate between two currencies.
         * @summary Update exchange rate
         * @param {UpdateExchangeRateRequest} updateExchangeRateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminExchangeRatesPut: async (updateExchangeRateRequest: UpdateExchangeRateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateExchangeRateRequest' is not null or undefined
            assertParamExists('apiV1WalletAdminExchangeRatesPut', 'updateExchangeRateRequest', updateExchangeRateRequest)
            const localVarPath = `/api/v1/wallet/admin/exchange-rates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateExchangeRateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves all merchants including inactive ones.
         * @summary Get all merchants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminMerchantsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/wallet/admin/merchants`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get merchant full info
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminMerchantsIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiV1WalletAdminMerchantsIdGet', 'id', id)
            const localVarPath = `/api/v1/wallet/admin/merchants/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update merchant
         * @param {string} id 
         * @param {UpdateMerchantRequest} updateMerchantRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminMerchantsIdPut: async (id: string, updateMerchantRequest: UpdateMerchantRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiV1WalletAdminMerchantsIdPut', 'id', id)
            // verify required parameter 'updateMerchantRequest' is not null or undefined
            assertParamExists('apiV1WalletAdminMerchantsIdPut', 'updateMerchantRequest', updateMerchantRequest)
            const localVarPath = `/api/v1/wallet/admin/merchants/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateMerchantRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create merchant
         * @param {CreateMerchantRequest} createMerchantRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminMerchantsPost: async (createMerchantRequest: CreateMerchantRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createMerchantRequest' is not null or undefined
            assertParamExists('apiV1WalletAdminMerchantsPost', 'createMerchantRequest', createMerchantRequest)
            const localVarPath = `/api/v1/wallet/admin/merchants`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createMerchantRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get admin dashboard summary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminSummaryGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/wallet/admin/summary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get user transactions
         * @param {string} userId 
         * @param {ApiV1WalletTransactionsGetLimitParameter} [limit] 
         * @param {ApiV1WalletTransactionsGetOffsetParameter} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminTransactionsUserIdGet: async (userId: string, limit?: ApiV1WalletTransactionsGetLimitParameter, offset?: ApiV1WalletTransactionsGetOffsetParameter, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('apiV1WalletAdminTransactionsUserIdGet', 'userId', userId)
            const localVarPath = `/api/v1/wallet/admin/transactions/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Adjust user wallet balance
         * @param {string} userId 
         * @param {AdjustBalanceRequest} adjustBalanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminWalletsUserIdAdjustPost: async (userId: string, adjustBalanceRequest: AdjustBalanceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('apiV1WalletAdminWalletsUserIdAdjustPost', 'userId', userId)
            // verify required parameter 'adjustBalanceRequest' is not null or undefined
            assertParamExists('apiV1WalletAdminWalletsUserIdAdjustPost', 'adjustBalanceRequest', adjustBalanceRequest)
            const localVarPath = `/api/v1/wallet/admin/wallets/{userId}/adjust`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(adjustBalanceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get user wallet
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminWalletsUserIdGet: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('apiV1WalletAdminWalletsUserIdGet', 'userId', userId)
            const localVarPath = `/api/v1/wallet/admin/wallets/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminApi - functional programming interface
 */
export const AdminApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all currencies (admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletAdminExchangeRatesCurrenciesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CurrencyResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletAdminExchangeRatesCurrenciesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.apiV1WalletAdminExchangeRatesCurrenciesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all exchange rates (admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletAdminExchangeRatesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ExchangeRateResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletAdminExchangeRatesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.apiV1WalletAdminExchangeRatesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the history of exchange rate changes.
         * @summary Get exchange rate history
         * @param {ApiV1WalletAdminExchangeRatesHistoryGetLimitParameter} limit 
         * @param {string} [sourceCurrency] 
         * @param {string} [targetCurrency] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletAdminExchangeRatesHistoryGet(limit: ApiV1WalletAdminExchangeRatesHistoryGetLimitParameter, sourceCurrency?: string, targetCurrency?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ExchangeRateHistoryResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletAdminExchangeRatesHistoryGet(limit, sourceCurrency, targetCurrency, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.apiV1WalletAdminExchangeRatesHistoryGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create or update an exchange rate between two currencies.
         * @summary Update exchange rate
         * @param {UpdateExchangeRateRequest} updateExchangeRateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletAdminExchangeRatesPut(updateExchangeRateRequest: UpdateExchangeRateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExchangeRateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletAdminExchangeRatesPut(updateExchangeRateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.apiV1WalletAdminExchangeRatesPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves all merchants including inactive ones.
         * @summary Get all merchants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletAdminMerchantsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MerchantResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletAdminMerchantsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.apiV1WalletAdminMerchantsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get merchant full info
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletAdminMerchantsIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MerchantModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletAdminMerchantsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.apiV1WalletAdminMerchantsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update merchant
         * @param {string} id 
         * @param {UpdateMerchantRequest} updateMerchantRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletAdminMerchantsIdPut(id: string, updateMerchantRequest: UpdateMerchantRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MerchantModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletAdminMerchantsIdPut(id, updateMerchantRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.apiV1WalletAdminMerchantsIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create merchant
         * @param {CreateMerchantRequest} createMerchantRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletAdminMerchantsPost(createMerchantRequest: CreateMerchantRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MerchantModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletAdminMerchantsPost(createMerchantRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.apiV1WalletAdminMerchantsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get admin dashboard summary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletAdminSummaryGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminSummaryModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletAdminSummaryGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.apiV1WalletAdminSummaryGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get user transactions
         * @param {string} userId 
         * @param {ApiV1WalletTransactionsGetLimitParameter} [limit] 
         * @param {ApiV1WalletTransactionsGetOffsetParameter} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletAdminTransactionsUserIdGet(userId: string, limit?: ApiV1WalletTransactionsGetLimitParameter, offset?: ApiV1WalletTransactionsGetOffsetParameter, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TransactionResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletAdminTransactionsUserIdGet(userId, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.apiV1WalletAdminTransactionsUserIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Adjust user wallet balance
         * @param {string} userId 
         * @param {AdjustBalanceRequest} adjustBalanceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletAdminWalletsUserIdAdjustPost(userId: string, adjustBalanceRequest: AdjustBalanceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WalletResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletAdminWalletsUserIdAdjustPost(userId, adjustBalanceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.apiV1WalletAdminWalletsUserIdAdjustPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get user wallet
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletAdminWalletsUserIdGet(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WalletResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletAdminWalletsUserIdGet(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminApi.apiV1WalletAdminWalletsUserIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminApi - factory interface
 */
export const AdminApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all currencies (admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminExchangeRatesCurrenciesGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<CurrencyResponse>> {
            return localVarFp.apiV1WalletAdminExchangeRatesCurrenciesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all exchange rates (admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminExchangeRatesGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<ExchangeRateResponse>> {
            return localVarFp.apiV1WalletAdminExchangeRatesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the history of exchange rate changes.
         * @summary Get exchange rate history
         * @param {AdminApiApiV1WalletAdminExchangeRatesHistoryGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminExchangeRatesHistoryGet(requestParameters: AdminApiApiV1WalletAdminExchangeRatesHistoryGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<ExchangeRateHistoryResponse>> {
            return localVarFp.apiV1WalletAdminExchangeRatesHistoryGet(requestParameters.limit, requestParameters.sourceCurrency, requestParameters.targetCurrency, options).then((request) => request(axios, basePath));
        },
        /**
         * Create or update an exchange rate between two currencies.
         * @summary Update exchange rate
         * @param {AdminApiApiV1WalletAdminExchangeRatesPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminExchangeRatesPut(requestParameters: AdminApiApiV1WalletAdminExchangeRatesPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<ExchangeRateResponse> {
            return localVarFp.apiV1WalletAdminExchangeRatesPut(requestParameters.updateExchangeRateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves all merchants including inactive ones.
         * @summary Get all merchants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminMerchantsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<MerchantResponse>> {
            return localVarFp.apiV1WalletAdminMerchantsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get merchant full info
         * @param {AdminApiApiV1WalletAdminMerchantsIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminMerchantsIdGet(requestParameters: AdminApiApiV1WalletAdminMerchantsIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<MerchantModel> {
            return localVarFp.apiV1WalletAdminMerchantsIdGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update merchant
         * @param {AdminApiApiV1WalletAdminMerchantsIdPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminMerchantsIdPut(requestParameters: AdminApiApiV1WalletAdminMerchantsIdPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<MerchantModel> {
            return localVarFp.apiV1WalletAdminMerchantsIdPut(requestParameters.id, requestParameters.updateMerchantRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create merchant
         * @param {AdminApiApiV1WalletAdminMerchantsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminMerchantsPost(requestParameters: AdminApiApiV1WalletAdminMerchantsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<MerchantModel> {
            return localVarFp.apiV1WalletAdminMerchantsPost(requestParameters.createMerchantRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get admin dashboard summary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminSummaryGet(options?: RawAxiosRequestConfig): AxiosPromise<AdminSummaryModel> {
            return localVarFp.apiV1WalletAdminSummaryGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get user transactions
         * @param {AdminApiApiV1WalletAdminTransactionsUserIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminTransactionsUserIdGet(requestParameters: AdminApiApiV1WalletAdminTransactionsUserIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<TransactionResponse>> {
            return localVarFp.apiV1WalletAdminTransactionsUserIdGet(requestParameters.userId, requestParameters.limit, requestParameters.offset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Adjust user wallet balance
         * @param {AdminApiApiV1WalletAdminWalletsUserIdAdjustPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminWalletsUserIdAdjustPost(requestParameters: AdminApiApiV1WalletAdminWalletsUserIdAdjustPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<WalletResponse> {
            return localVarFp.apiV1WalletAdminWalletsUserIdAdjustPost(requestParameters.userId, requestParameters.adjustBalanceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get user wallet
         * @param {AdminApiApiV1WalletAdminWalletsUserIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletAdminWalletsUserIdGet(requestParameters: AdminApiApiV1WalletAdminWalletsUserIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<WalletResponse> {
            return localVarFp.apiV1WalletAdminWalletsUserIdGet(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiV1WalletAdminExchangeRatesHistoryGet operation in AdminApi.
 */
export interface AdminApiApiV1WalletAdminExchangeRatesHistoryGetRequest {
    readonly limit: ApiV1WalletAdminExchangeRatesHistoryGetLimitParameter

    readonly sourceCurrency?: string

    readonly targetCurrency?: string
}

/**
 * Request parameters for apiV1WalletAdminExchangeRatesPut operation in AdminApi.
 */
export interface AdminApiApiV1WalletAdminExchangeRatesPutRequest {
    readonly updateExchangeRateRequest: UpdateExchangeRateRequest
}

/**
 * Request parameters for apiV1WalletAdminMerchantsIdGet operation in AdminApi.
 */
export interface AdminApiApiV1WalletAdminMerchantsIdGetRequest {
    readonly id: string
}

/**
 * Request parameters for apiV1WalletAdminMerchantsIdPut operation in AdminApi.
 */
export interface AdminApiApiV1WalletAdminMerchantsIdPutRequest {
    readonly id: string

    readonly updateMerchantRequest: UpdateMerchantRequest
}

/**
 * Request parameters for apiV1WalletAdminMerchantsPost operation in AdminApi.
 */
export interface AdminApiApiV1WalletAdminMerchantsPostRequest {
    readonly createMerchantRequest: CreateMerchantRequest
}

/**
 * Request parameters for apiV1WalletAdminTransactionsUserIdGet operation in AdminApi.
 */
export interface AdminApiApiV1WalletAdminTransactionsUserIdGetRequest {
    readonly userId: string

    readonly limit?: ApiV1WalletTransactionsGetLimitParameter

    readonly offset?: ApiV1WalletTransactionsGetOffsetParameter
}

/**
 * Request parameters for apiV1WalletAdminWalletsUserIdAdjustPost operation in AdminApi.
 */
export interface AdminApiApiV1WalletAdminWalletsUserIdAdjustPostRequest {
    readonly userId: string

    readonly adjustBalanceRequest: AdjustBalanceRequest
}

/**
 * Request parameters for apiV1WalletAdminWalletsUserIdGet operation in AdminApi.
 */
export interface AdminApiApiV1WalletAdminWalletsUserIdGetRequest {
    readonly userId: string
}

/**
 * AdminApi - object-oriented interface
 */
export class AdminApi extends BaseAPI {
    /**
     * 
     * @summary Get all currencies (admin)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletAdminExchangeRatesCurrenciesGet(options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).apiV1WalletAdminExchangeRatesCurrenciesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all exchange rates (admin)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletAdminExchangeRatesGet(options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).apiV1WalletAdminExchangeRatesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the history of exchange rate changes.
     * @summary Get exchange rate history
     * @param {AdminApiApiV1WalletAdminExchangeRatesHistoryGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletAdminExchangeRatesHistoryGet(requestParameters: AdminApiApiV1WalletAdminExchangeRatesHistoryGetRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).apiV1WalletAdminExchangeRatesHistoryGet(requestParameters.limit, requestParameters.sourceCurrency, requestParameters.targetCurrency, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create or update an exchange rate between two currencies.
     * @summary Update exchange rate
     * @param {AdminApiApiV1WalletAdminExchangeRatesPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletAdminExchangeRatesPut(requestParameters: AdminApiApiV1WalletAdminExchangeRatesPutRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).apiV1WalletAdminExchangeRatesPut(requestParameters.updateExchangeRateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves all merchants including inactive ones.
     * @summary Get all merchants
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletAdminMerchantsGet(options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).apiV1WalletAdminMerchantsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get merchant full info
     * @param {AdminApiApiV1WalletAdminMerchantsIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletAdminMerchantsIdGet(requestParameters: AdminApiApiV1WalletAdminMerchantsIdGetRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).apiV1WalletAdminMerchantsIdGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update merchant
     * @param {AdminApiApiV1WalletAdminMerchantsIdPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletAdminMerchantsIdPut(requestParameters: AdminApiApiV1WalletAdminMerchantsIdPutRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).apiV1WalletAdminMerchantsIdPut(requestParameters.id, requestParameters.updateMerchantRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create merchant
     * @param {AdminApiApiV1WalletAdminMerchantsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletAdminMerchantsPost(requestParameters: AdminApiApiV1WalletAdminMerchantsPostRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).apiV1WalletAdminMerchantsPost(requestParameters.createMerchantRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get admin dashboard summary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletAdminSummaryGet(options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).apiV1WalletAdminSummaryGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get user transactions
     * @param {AdminApiApiV1WalletAdminTransactionsUserIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletAdminTransactionsUserIdGet(requestParameters: AdminApiApiV1WalletAdminTransactionsUserIdGetRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).apiV1WalletAdminTransactionsUserIdGet(requestParameters.userId, requestParameters.limit, requestParameters.offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Adjust user wallet balance
     * @param {AdminApiApiV1WalletAdminWalletsUserIdAdjustPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletAdminWalletsUserIdAdjustPost(requestParameters: AdminApiApiV1WalletAdminWalletsUserIdAdjustPostRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).apiV1WalletAdminWalletsUserIdAdjustPost(requestParameters.userId, requestParameters.adjustBalanceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get user wallet
     * @param {AdminApiApiV1WalletAdminWalletsUserIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletAdminWalletsUserIdGet(requestParameters: AdminApiApiV1WalletAdminWalletsUserIdGetRequest, options?: RawAxiosRequestConfig) {
        return AdminApiFp(this.configuration).apiV1WalletAdminWalletsUserIdGet(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ExchangeRatesApi - axios parameter creator
 */
export const ExchangeRatesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get applied exchange rates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletExchangeRatesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/wallet/exchange-rates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExchangeRatesApi - functional programming interface
 */
export const ExchangeRatesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExchangeRatesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get applied exchange rates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletExchangeRatesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ExchangeRateResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletExchangeRatesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExchangeRatesApi.apiV1WalletExchangeRatesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExchangeRatesApi - factory interface
 */
export const ExchangeRatesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExchangeRatesApiFp(configuration)
    return {
        /**
         * 
         * @summary Get applied exchange rates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletExchangeRatesGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<ExchangeRateResponse>> {
            return localVarFp.apiV1WalletExchangeRatesGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ExchangeRatesApi - object-oriented interface
 */
export class ExchangeRatesApi extends BaseAPI {
    /**
     * 
     * @summary Get applied exchange rates
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletExchangeRatesGet(options?: RawAxiosRequestConfig) {
        return ExchangeRatesApiFp(this.configuration).apiV1WalletExchangeRatesGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MerchantApi - axios parameter creator
 */
export const MerchantApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves a list of active merchants.
         * @summary Get active merchants
         * @param {string} [countryCode] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletMerchantsGet: async (countryCode?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/wallet/merchants`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (countryCode !== undefined) {
                localVarQueryParameter['countryCode'] = countryCode;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves details of a specific merchant by ID.
         * @summary Get merchant details
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletMerchantsIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiV1WalletMerchantsIdGet', 'id', id)
            const localVarPath = `/api/v1/wallet/merchants/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MerchantApi - functional programming interface
 */
export const MerchantApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MerchantApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves a list of active merchants.
         * @summary Get active merchants
         * @param {string} [countryCode] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletMerchantsGet(countryCode?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MerchantResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletMerchantsGet(countryCode, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MerchantApi.apiV1WalletMerchantsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves details of a specific merchant by ID.
         * @summary Get merchant details
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletMerchantsIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MerchantResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletMerchantsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MerchantApi.apiV1WalletMerchantsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MerchantApi - factory interface
 */
export const MerchantApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MerchantApiFp(configuration)
    return {
        /**
         * Retrieves a list of active merchants.
         * @summary Get active merchants
         * @param {MerchantApiApiV1WalletMerchantsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletMerchantsGet(requestParameters: MerchantApiApiV1WalletMerchantsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<MerchantResponse>> {
            return localVarFp.apiV1WalletMerchantsGet(requestParameters.countryCode, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves details of a specific merchant by ID.
         * @summary Get merchant details
         * @param {MerchantApiApiV1WalletMerchantsIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletMerchantsIdGet(requestParameters: MerchantApiApiV1WalletMerchantsIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<MerchantResponse> {
            return localVarFp.apiV1WalletMerchantsIdGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiV1WalletMerchantsGet operation in MerchantApi.
 */
export interface MerchantApiApiV1WalletMerchantsGetRequest {
    readonly countryCode?: string
}

/**
 * Request parameters for apiV1WalletMerchantsIdGet operation in MerchantApi.
 */
export interface MerchantApiApiV1WalletMerchantsIdGetRequest {
    readonly id: string
}

/**
 * MerchantApi - object-oriented interface
 */
export class MerchantApi extends BaseAPI {
    /**
     * Retrieves a list of active merchants.
     * @summary Get active merchants
     * @param {MerchantApiApiV1WalletMerchantsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletMerchantsGet(requestParameters: MerchantApiApiV1WalletMerchantsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return MerchantApiFp(this.configuration).apiV1WalletMerchantsGet(requestParameters.countryCode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves details of a specific merchant by ID.
     * @summary Get merchant details
     * @param {MerchantApiApiV1WalletMerchantsIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletMerchantsIdGet(requestParameters: MerchantApiApiV1WalletMerchantsIdGetRequest, options?: RawAxiosRequestConfig) {
        return MerchantApiFp(this.configuration).apiV1WalletMerchantsIdGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PaymentApi - axios parameter creator
 */
export const PaymentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Processes a payment transaction for a user.
         * @summary Process a payment
         * @param {PaymentRequest} paymentRequest 
         * @param {string} [xIdempotencyKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletPaymentsPost: async (paymentRequest: PaymentRequest, xIdempotencyKey?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paymentRequest' is not null or undefined
            assertParamExists('apiV1WalletPaymentsPost', 'paymentRequest', paymentRequest)
            const localVarPath = `/api/v1/wallet/payments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xIdempotencyKey != null) {
                localVarHeaderParameter['X-Idempotency-Key'] = String(xIdempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(paymentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentApi - functional programming interface
 */
export const PaymentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaymentApiAxiosParamCreator(configuration)
    return {
        /**
         * Processes a payment transaction for a user.
         * @summary Process a payment
         * @param {PaymentRequest} paymentRequest 
         * @param {string} [xIdempotencyKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletPaymentsPost(paymentRequest: PaymentRequest, xIdempotencyKey?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletPaymentsPost(paymentRequest, xIdempotencyKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentApi.apiV1WalletPaymentsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PaymentApi - factory interface
 */
export const PaymentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaymentApiFp(configuration)
    return {
        /**
         * Processes a payment transaction for a user.
         * @summary Process a payment
         * @param {PaymentApiApiV1WalletPaymentsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletPaymentsPost(requestParameters: PaymentApiApiV1WalletPaymentsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<PaymentResponse> {
            return localVarFp.apiV1WalletPaymentsPost(requestParameters.paymentRequest, requestParameters.xIdempotencyKey, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiV1WalletPaymentsPost operation in PaymentApi.
 */
export interface PaymentApiApiV1WalletPaymentsPostRequest {
    readonly paymentRequest: PaymentRequest

    readonly xIdempotencyKey?: string
}

/**
 * PaymentApi - object-oriented interface
 */
export class PaymentApi extends BaseAPI {
    /**
     * Processes a payment transaction for a user.
     * @summary Process a payment
     * @param {PaymentApiApiV1WalletPaymentsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletPaymentsPost(requestParameters: PaymentApiApiV1WalletPaymentsPostRequest, options?: RawAxiosRequestConfig) {
        return PaymentApiFp(this.configuration).apiV1WalletPaymentsPost(requestParameters.paymentRequest, requestParameters.xIdempotencyKey, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TransactionApi - axios parameter creator
 */
export const TransactionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves a list of past transactions for the authenticated user.
         * @summary Get transaction history
         * @param {ApiV1WalletTransactionsGetLimitParameter} [limit] 
         * @param {ApiV1WalletTransactionsGetOffsetParameter} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletTransactionsGet: async (limit?: ApiV1WalletTransactionsGetLimitParameter, offset?: ApiV1WalletTransactionsGetOffsetParameter, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/wallet/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransactionApi - functional programming interface
 */
export const TransactionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransactionApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves a list of past transactions for the authenticated user.
         * @summary Get transaction history
         * @param {ApiV1WalletTransactionsGetLimitParameter} [limit] 
         * @param {ApiV1WalletTransactionsGetOffsetParameter} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletTransactionsGet(limit?: ApiV1WalletTransactionsGetLimitParameter, offset?: ApiV1WalletTransactionsGetOffsetParameter, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TransactionResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletTransactionsGet(limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionApi.apiV1WalletTransactionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TransactionApi - factory interface
 */
export const TransactionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransactionApiFp(configuration)
    return {
        /**
         * Retrieves a list of past transactions for the authenticated user.
         * @summary Get transaction history
         * @param {TransactionApiApiV1WalletTransactionsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletTransactionsGet(requestParameters: TransactionApiApiV1WalletTransactionsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<TransactionResponse>> {
            return localVarFp.apiV1WalletTransactionsGet(requestParameters.limit, requestParameters.offset, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiV1WalletTransactionsGet operation in TransactionApi.
 */
export interface TransactionApiApiV1WalletTransactionsGetRequest {
    readonly limit?: ApiV1WalletTransactionsGetLimitParameter

    readonly offset?: ApiV1WalletTransactionsGetOffsetParameter
}

/**
 * TransactionApi - object-oriented interface
 */
export class TransactionApi extends BaseAPI {
    /**
     * Retrieves a list of past transactions for the authenticated user.
     * @summary Get transaction history
     * @param {TransactionApiApiV1WalletTransactionsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletTransactionsGet(requestParameters: TransactionApiApiV1WalletTransactionsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return TransactionApiFp(this.configuration).apiV1WalletTransactionsGet(requestParameters.limit, requestParameters.offset, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WalletApi - axios parameter creator
 */
export const WalletApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Charges the user\'s Money wallet with the specified amount.
         * @summary Charge wallet
         * @param {ChargeRequest} chargeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletChargePost: async (chargeRequest: ChargeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chargeRequest' is not null or undefined
            assertParamExists('apiV1WalletChargePost', 'chargeRequest', chargeRequest)
            const localVarPath = `/api/v1/wallet/charge`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(chargeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the current user\'s Money wallet information.
         * @summary Get my wallet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletMeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/wallet/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WalletApi - functional programming interface
 */
export const WalletApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WalletApiAxiosParamCreator(configuration)
    return {
        /**
         * Charges the user\'s Money wallet with the specified amount.
         * @summary Charge wallet
         * @param {ChargeRequest} chargeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletChargePost(chargeRequest: ChargeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WalletResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletChargePost(chargeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WalletApi.apiV1WalletChargePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves the current user\'s Money wallet information.
         * @summary Get my wallet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1WalletMeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WalletResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1WalletMeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WalletApi.apiV1WalletMeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WalletApi - factory interface
 */
export const WalletApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WalletApiFp(configuration)
    return {
        /**
         * Charges the user\'s Money wallet with the specified amount.
         * @summary Charge wallet
         * @param {WalletApiApiV1WalletChargePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletChargePost(requestParameters: WalletApiApiV1WalletChargePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<WalletResponse> {
            return localVarFp.apiV1WalletChargePost(requestParameters.chargeRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the current user\'s Money wallet information.
         * @summary Get my wallet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1WalletMeGet(options?: RawAxiosRequestConfig): AxiosPromise<WalletResponse> {
            return localVarFp.apiV1WalletMeGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiV1WalletChargePost operation in WalletApi.
 */
export interface WalletApiApiV1WalletChargePostRequest {
    readonly chargeRequest: ChargeRequest
}

/**
 * WalletApi - object-oriented interface
 */
export class WalletApi extends BaseAPI {
    /**
     * Charges the user\'s Money wallet with the specified amount.
     * @summary Charge wallet
     * @param {WalletApiApiV1WalletChargePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletChargePost(requestParameters: WalletApiApiV1WalletChargePostRequest, options?: RawAxiosRequestConfig) {
        return WalletApiFp(this.configuration).apiV1WalletChargePost(requestParameters.chargeRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the current user\'s Money wallet information.
     * @summary Get my wallet
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1WalletMeGet(options?: RawAxiosRequestConfig) {
        return WalletApiFp(this.configuration).apiV1WalletMeGet(options).then((request) => request(this.axios, this.basePath));
    }
}



